#+title: Project sketchbook
#+author: Henrique Silva
#+author: Felipe Colombelli
#+email: hcpsilva@inf.ufrgs.br
#+infojs_opt:

* Feedback da correção

Na leitura do relatório da professora eu listei os seguintes itens como
importantes pra gente resolver.

** Universo de discurso

A natureza das observações da professora só ressalta que ela realmente não abriu
o site para checar suas presunções, especulações e dúvidas.

Enfim, considerando a afirmação anterior, seria interessante nós explicarmos
melhor os seguintes itens da descrição do UdD:

- [ ] "ou coletados de outras fontes"
  Eu genuinamente fiquei confuso nessa parte, que outras fontes? Pensei que o
  exploit-db só lidasse com submissões dos usuários.
- [ ] Deixar mais claro que não existe grande formalidade para submissões, a
  final, a categorização dessas é feita à mão pelos moderadores do site. Pra mim
  fica até claro que, originalmente, o site deveria somente conter exploits. Num
  segundo momento eles decidiram colocar mais coisas usando o mesmo sistema!
- [ ] Colocar que shellcode tem tamanho!
- [ ] Deixar claro que a submissão verificável carrega também um status de se já
  foi verificada ou não.
- [ ] Dizer que plataforma é o sistema operacional/arquitetura...
- [ ] Deixar mais clara a diferença entre incidente e vazamento (eu tive uma
  dúvida similar até né)
- [ ] Infelizmente a exploit-db não guarda muitas infos sobre os aplicativos com
  vulnerabilidades não professora...

** Modelo ER

Fora as coisas que faltaram no UdD, não sei se nós erramos alguma coisa aqui.

Coisas que faltam ou precisam ser arrumadas:

- [ ] Status da verificação em verificável
- [ ] Nome do enviável
- [ ] Plataforma de artigo é opcional
- [ ] Nomes melhores para a entidade aplicativo

* Consultas

* Procedimentos armazenados

* Programa
