#+title: Project sketchbook
#+author: Henrique Silva
#+author: Felipe Colombelli
#+email: hcpsilva@inf.ufrgs.br
#+infojs_opt:

* Feedback da correção

Na leitura do relatório da professora eu listei os seguintes itens como
importantes pra gente resolver.

** Universo de discurso

A natureza das observações da professora só ressalta que ela realmente não abriu
o site para checar suas presunções, especulações e dúvidas.

Enfim, considerando a afirmação anterior, seria interessante nós explicarmos
melhor os seguintes itens da descrição do UdD:

- [X] "ou coletados de outras fontes"
  Eu genuinamente fiquei confuso nessa parte, que outras fontes? Pensei que o
  exploit-db só lidasse com submissões dos usuários.
- [X] Deixar mais claro que não existe grande formalidade para submissões, a
  final, a categorização dessas é feita à mão pelos moderadores do site. Pra mim
  fica até claro que, originalmente, o site deveria somente conter exploits. Num
  segundo momento eles decidiram colocar mais coisas usando o mesmo sistema!
- [X] Colocar que shellcode tem tamanho!
- [X] Deixar claro que a submissão verificável carrega também um status de se já
  foi verificada ou não.
- [X] Dizer que plataforma é o sistema operacional/arquitetura...
- [X] Deixar mais clara a diferença entre incidente e vazamento (eu tive uma
  dúvida similar até né)
- [X] Infelizmente a exploit-db não guarda muitas infos sobre os aplicativos com
  vulnerabilidades não professora...

** Modelo ER

Fora as coisas que faltaram no UdD, não sei se nós erramos alguma coisa aqui.

Coisas que faltam ou precisam ser arrumadas:

- [X] Status da verificação em verificável
- [X] Nome do enviável
- [X] Plataforma de artigo é opcional
- [X] Nomes melhores para a entidade aplicativo

* Consultas

Nessa sessão é pra ficar as ideias e as consultas implementadas até o momento.

** Brainstorming

- Todos os exploits explorados por um determinado usuário na plataforma Linux
- Todos os dados de vazamentos associados a um dado usuário do ExploitDB, assim
  como quais dados pessoais foram vazados.
- Todos os dados de aplicativos associados a determinado CVE.
- Os verificadores que verificaram Shellcodes, ordenados pelo tamanho médio dos
  shellcodes que eles verificaram.
- Os dados de vazamentos dos usuários que tiveram seus dados vazados nos mesmos
  sites (e talvez outros) que um dado usuário.
- Os verificáveis que ainda não foram verificados e cuja plataforma é a que
  possui o maior número de artigos associados.

* Visão

Todos os enviáveis que não foram revisados ainda.

- E que foram enviados antes de uma dada data
- E que são exploits relacionados a um CVE.

* Procedimentos armazenados

Procedimentos! A coisa mais inútil ever.

Verificar se o email é válido e a senha contém no mínimo coisas...

* Programa
